### ISSUE TITLE
[BUG] Unable to build 1.4.33 for armv7-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by kjlaw89** [fltk-rs/fltk-rs#1577]
OS: Ubuntu 20.04.6
Version: 1.4.33
Display server: X11

Successfully compiles on 1.4.32.

Output:

```
error[E0308]: mismatched types
   --> /home/dc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fltk-1.4.33/src/window.rs:419:25
    |
417 |                     XMapWindow(
    |                     ---------- arguments to this function are incorrect
418 |                         crate::app::display() as _,
419 |                         self.raw_handle() as RawXlibHandle,
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u64`, found `u32`
    |
note: function defined here
   --> /home/dc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fltk-1.4.33/src/window.rs:415:28
    |
415 |                         fn XMapWindow(display: *mut Display, win: u64);
    |                            ^^^^^^^^^^
help: you can convert a `u32` to a `u64`
    |
419 |                         (self.raw_handle() as RawXlibHandle).into(),
    |                         +                                  ++++++++

error[E0308]: mismatched types
   --> /home/dc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fltk-1.4.33/src/window.rs:456:25
    |
454 |                     XUnmapWindow(
    |                     ------------ arguments to this function are incorrect
455 |                         crate::app::display() as _,
456 |                         self.raw_handle() as RawXlibHandle,
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u64`, found `u32`
    |
note: function defined here
   --> /home/dc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fltk-1.4.33/src/window.rs:452:28
    |
452 |                         fn XUnmapWindow(display: *mut Display, win: u64);
    |                            ^^^^^^^^^^^^
help: you can convert a `u32` to a `u64`
    |
456 |                         (self.raw_handle() as RawXlibHandle).into(),
    |                         +                                  ++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `fltk` (lib) due to 2 previous errors
```

**Comment by kjlaw89** [comment]
Seems that this has been fixed in the repo - pulling directly from git and compiling worked fine. Going to close this out.
